// Generated by CoffeeScript 1.4.0
var Node, SortedCircularDoublyLinkedList;

Node = (function() {

  function Node(datum, prev, next) {
    this.datum = datum;
    this.prev = prev;
    this.next = next;
  }

  return Node;

})();

SortedCircularDoublyLinkedList = (function() {

  function SortedCircularDoublyLinkedList(head, tail) {
    this.head = head;
    this.tail = tail;
  }

  SortedCircularDoublyLinkedList.prototype.compare = function(datum1, datum2) {
    return datum1 - datum2;
  };

  SortedCircularDoublyLinkedList.prototype.insertAll = function(list) {
    var x, _i, _len;
    if (list == null) {
      list = [];
    }
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      x = list[_i];
      this.insert(x);
    }
    return this.head;
  };

  SortedCircularDoublyLinkedList.prototype.insert = function(datum) {
    var current, insertAfter, insertBefore, next, node;
    node = new Node(datum);
    insertBefore = function(a, b) {
      if (b === this.head) {
        a.prev = this.tail;
        this.head = a;
        this.tail.next = this.head;
      } else {
        a.prev = b.prev;
        b.prev.next = a;
      }
      a.next = b;
      return b.prev = a;
    };
    insertAfter = function(a, b) {
      if (b === this.tail) {
        a.next = this.head;
        this.tail = a;
        this.head.prev = this.tail;
      } else {
        a.next = b.next;
        b.next.prev = a;
      }
      a.prev = b;
      return b.next = a;
    };
    if (this.head == null) {
      this.head = node;
      this.head.next = node;
      this.head.prev = node;
      this.tail = this.head;
      return node;
    }
    if (this.compare(this.head.datum, node.datum) > 0) {
      insertBefore(node, this.head);
    } else {
      current = this.head;
      while (current !== this.tail) {
        next = current.next;
        if (this.compare(next.datum, node.datum) > 0) {
          break;
        }
        current = current.next;
      }
      insertAfter(node, current);
    }
    if (this.compare(node.datum, this.head.datum) < 0) {
      this.head = node;
    }
    if (this.compare(node.datum, this.tail.datum) > 0) {
      this.tail = node;
    }
    return node;
  };

  SortedCircularDoublyLinkedList.prototype.remove = function(datum) {
    var current;
    current = this.head;
    while (this.compare(current.datum, datum) !== 0) {
      current = current.next;
      if (current === this.head) {
        return;
      }
    }
    if (current === this.head) {
      this.head = current.next;
      this.tail.next = this.head;
      this.head.prev = this.tail;
    } else {
      current.prev.next = current.next;
    }
    if (current === this.tail) {
      this.tail = current.prev;
      this.head.prev = this.tail;
      return this.tail.next = this.head;
    } else {
      return current.next.prev = current.prev;
    }
  };

  SortedCircularDoublyLinkedList.prototype.contains = function(datum) {
    return this.find(datum) != null;
  };

  SortedCircularDoublyLinkedList.prototype.find = function(datum) {
    var current;
    if (!this.head) {
      return null;
    } else {
      current = this.head;
      while (current.next !== this.head) {
        if (this.compare(current.datum, datum) === 0) {
          return current;
        }
        current = current.next;
      }
      return null;
    }
  };

  SortedCircularDoublyLinkedList.prototype.print = function() {
    var current, output;
    output = "";
    if (!(this.head != null)) {
      return;
    }
    current = this.head;
    output += "" + current.datum;
    while (current.next !== this.head) {
      current = current.next;
      output += ", " + current.datum;
    }
    return output;
  };

  return SortedCircularDoublyLinkedList;

})();
